### ISSUE TITLE
consider support --reference option in clone

### ISSUE THREAD

**Issue by markdingram** [flosell/lambdacd-git#13]
From git-clone docs:

--reference <repository>

```
If the reference repository is on the local machine, automatically setup .git/objects/info/alternates to obtain objects from the reference repository. Using an already existing repository as an alternate will require fewer objects to be copied from the repository being cloned, reducing network and local storage costs.
```

This is invaluable to speed up CI on larger repos.

Unfortunately JGit Clone doesn't expose this option. Jenkins have worked around it via 
https://github.com/jenkinsci/git-client-plugin/blob/master/src/main/java/org/jenkinsci/plugins/gitclient/JGitAPIImpl.java#L1382

**Comment by markdingram** [comment]
I have a crude port of the Jenkins approach to Clojure. If interested let me know and I can polish it for a PR.

**Comment by flosell** [comment]
Hmm, looks interesting. I'm happy to give feedback on a work-in-progress PR that you can polish once we feel like it's going in the right direction.

**Comment by markdingram** [comment]
BFG was able to reduce the repo back to a manageable size, so pursuing this wasn't necessary.

Crude code as mentioned above for anyone else who finds themselves in this situation:
https://gist.github.com/markdingram/0130c1be1b1eac7b3e14f6cb80d25307

**Comment by flosell** [comment]
Thanks for the feedback and the code! I'm closing this issue for now, anyone with an interest in this, feel free to comment and we'll reopen this.
