### ISSUE TITLE
Authentication with ssh-key

### ISSUE THREAD

**Issue by p4ulcristian** [flosell/lambdacd-git#26]
Hello, I try to use lambdacd with one of my repos, but I tried it with yours aswell, and I get the same error everytime

> Cloning git@github.com:paul931224/Testing-LambdaCD-in-production-enviroment ...
TransportException git@github.com:paul931224/Testing-LambdaCD-in-production-enviroment: USERAUTH fail
org.eclipse.jgit.api.FetchCommand.call (FetchCommand.java:139)
org.eclipse.jgit.api.CloneCommand.fetch (CloneCommand.java:200)
org.eclipse.jgit.api.CloneCommand.call (CloneCommand.java:134)
org.eclipse.jgit.api.CloneCommand.call (CloneCommand.java:83)
sun.reflect.NativeMethodAccessorImpl.invoke0 (NativeMethodAccessorImpl.java:-2)
sun.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
sun.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
java.lang.reflect.Method.invoke (Method.java:498)
clojure.lang.Reflector.invokeMatchingMethod (Reflector.java:93)
clojure.lang.Reflector.invokeNoArgInstanceMember (Reflector.java:313)
lambdacd-git.git/clone-repo (git.clj:98)
lambdacd-git.git/clone-repo (git.clj:91)
Caused by:
TransportException git@github.com:paul931224/Testing-LambdaCD-in-production-enviroment: USERAUTH fail
org.eclipse.jgit.transport.JschConfigSessionFactory.getSession (JschConfigSessionFactory.java:159)
lambdacd_git.ssh.proxy$org.eclipse.jgit.transport.JschConfigSessionFactory$ff19274a.getSession (:-1)
org.eclipse.jgit.transport.SshTransport.getSession (SshTransport.java:136)
org.eclipse.jgit.transport.TransportGitSsh$SshFetchConnection.<init> (TransportGitSsh.java:262)
org.eclipse.jgit.transport.TransportGitSsh.openFetch (TransportGitSsh.java:161)
org.eclipse.jgit.transport.FetchProcess.executeImp (FetchProcess.java:136)
org.eclipse.jgit.transport.FetchProcess.execute (FetchProcess.java:122)
org.eclipse.jgit.transport.Transport.fetch (Transport.java:1138)
org.eclipse.jgit.api.FetchCommand.call (FetchCommand.java:130)
org.eclipse.jgit.api.CloneCommand.fetch (CloneCommand.java:200)
Caused by:
JSchException USERAUTH fail
com.jcraft.jsch.UserAuthPublicKey.start (UserAuthPublicKey.java:119)
com.jcraft.jsch.Session.connect (Session.java:463)
org.eclipse.jgit.transport.JschConfigSessionFactory.getSession (JschConfigSessionFactory.java:116)
lambdacd_git.ssh.proxy$org.eclipse.jgit.transport.JschConfigSessionFactory$ff19274a.getSession (:-1)

I have my ssh key in the .ssh/ folder, and config is as in the tutorial. Where am I wrong? :/
```clojure
(defn clone [args ctx]
  (lambdacd-git/clone ctx "git@github.com:paul931224/Testing-LambdaCD-in-production-enviroment" "master" (:cwd args)))
```

```clojure
config   {:home-dir home-dir
                :name     "The future of my apps"
                :git {:timeout              20                       
                        :credentials-provider (UsernamePasswordCredentialsProvider/getDefault)}
                :ssh {:use-agent                true                      
                         :known-hosts-files        ["~/.ssh/known_hosts"
                                                   "/etc/ssh/ssh_known_hosts"]
      SSH connections
                        :identity-file            nil                      
                        :strict-host-key-checking nil}}
```

Thank you in advance! I appreaciate your work, this library would change the way I can provide apps!

**Comment by flosell** [comment]
`USERAUTH fail` is often related to keys that have a passphrase. If the key you are trying to use has one, make sure it's `ssh-add`ed it to your ssh-agent, LambdaCD should pick it up then. 

We have also seen some interesting JGit/Jsch (which `lambdacd-git` uses under the hood) behaviours with some more complex SSH configurations (e.g. #23) so if you are using some special configuration (e.g. non-standard locations/names for your keys, special configuration options or configuration not in `~/.ssh/config`), this might also be a cause for problems. 

This is hard to debug remotely but please post with what you find, maybe there's something we can do fix these things or at least make them easier to debug.

**Comment by p4ulcristian** [comment]
Thank you very much, `ssh-add`ing the private key worked! I didn't thought of it, because it works with my servers, I guess I should learn more about ssh-keys! :)

**Comment by jeremyvdw** [comment]
For the record I had the same issue but the culprit was in `~/.ssh/config`, here is what I had:
```
Host *
StrictHostKeyChecking no
IdentityFile          ~/.ssh/id_rsa
```
I had to comment `IdentityFile..` line to make it work, even though `~/.ssh/id_rsa` was my github key..
