### ISSUE TITLE
turn off (default) polling

### ISSUE THREAD

**Issue by Kobe** [flosell/lambdacd-git#31]
@flosell how you can turn off polling? if I don't pass this option if falls back to default.

should I use 0 (zero) as value?

**Comment by flosell** [comment]
Hi @Kobe, at the moment there's no such option. May I ask what your use-case for this is? If you rely on web- or post-commit hooks to detect changes, I'd suggest to just set a long polling interval. 

Given the polling is infrequent enough not to cause a load-issue on your git-server, it shouldn't hurt much and it makes the whole thing more reliable, e.g. in case someone disables git-hooks or your git-server doesn't send web-hooks for some reason (I've seen that happen in rare cases)

**Comment by Kobe** [comment]
Thanks for clarification
