### ISSUE TITLE
wait-for-git detects commit that was already built as new commit

### ISSUE THREAD

**Issue by flosell** [flosell/lambdacd-git#8]
- Build 7: 
  
  ```
  Last seen revisions: {refs/heads/master f88b3cacbd2356f9f7da2175fb0fe911f40cd955} . Waiting for new commit...
  Received notification. Polling out of schedule
  Found new commit:  9539c1f521a842507c16495e09a10628985f584b on refs/heads/master
  ```
- Stop and start LambdaCD, pointing to the same home-dir as before
- Build 8: 
  
  ```
  Last seen revisions: {:refs/heads/master 9539c1f521a842507c16495e09a10628985f584b} . Waiting for new commit...
  Found new commit:  9539c1f521a842507c16495e09a10628985f584b on refs/heads/master
  ```

Notice how build 8 finds the same SHA as in Build 7. Also, the last seen revisions suddenly are a keyword...

**Comment by philwhln** [comment]
I've seen this, but hadn't got around to digging into it whether I was doing something wrong. Glad you found the reason!

**Comment by flosell** [comment]
This should now be fixed upstream in the default LambdaCD persistence (#101). 

Not sure if users of [lambdacd-mongodb](https://github.com/SimonMonecke/lambdacd-mongodb) are affected in a similar way

**Comment by flosell** [comment]
[lambdacd-mongodb](https://github.com/SimonMonecke/lambdacd-mongodb) likely has the same problem, opened an issue there. 

Nothing more to do here, closing this for now. 

@philwhln: Thanks for the feedback by the way!
